#ifndef ASSETS_H
#define ASSETS_H

#define ASSETS_QUANTIDADE_CARROS 3
#define ASSETS_QUANTIDADE_ONIBUS 2

extern const char *ASSETS_CAMINHO_CARRO_JOGADOR;
extern const char *ASSETS_CAMINHO_PISTA;
extern const char *ASSETS_CAMINHOS_CARROS[ASSETS_QUANTIDADE_CARROS];
extern const char *ASSETS_CAMINHOS_ONIBUS[ASSETS_QUANTIDADE_ONIBUS];

#endif
